### ISSUE TITLE
inline styles from external files

### ISSUE THREAD

**Issue by emilos** [buxlabs/boxwood#274]
input:

main.css

```css
.foo { color: red }
```

index.html

```html
<link href="main.css" inline>
```

output:

index.html

```html
<style>.foo { color: red }</style>
```
