### ISSUE TITLE
Better error handling when YAML translation is unparseable

### ISSUE THREAD

**Issue by emilos** [buxlabs/boxwood#643]
In the example above, space is missing in line `en:bar`.

```yaml
i18n:
  pl: foo
  en:bar
```

Right now it's pretty hard to narrow down the problem. We should add a better error handling.
