### ISSUE TITLE
Better error handling when data tag contains duplicate translations

### ISSUE THREAD

**Issue by cieplus** [buxlabs/boxwood#647]
```yaml
<data yaml>
i18n:
  buy_now:
    pl: Kup teraz
    en: Buy now
  foo:
    pl: foo
    en: foo
  buy_now:
    pl: Kup teraz
    en: Buy now
</data>
```
